# Generated by Django 4.2.26 on 2025-12-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paneliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('pays_origine', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cv_fichier', models.FileField(help_text='PDF ou Word', upload_to='cv_panelistes/', verbose_name='CV / Biographie')),
                ('theme', models.CharField(max_length=300, verbose_name='Thème à aborder')),
                ('message', models.TextField(verbose_name='Message complémentaire')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Panéliste',
                'verbose_name_plural': 'Panélistes',
                'ordering': ['-date_candidature'],
            },
        ),
    ]
