# Generated by Django 4.2.26 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelistes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneliste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='panelistes/', verbose_name='Photo'),
        ),
    ]
