# Generated by Django 4.2.26 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelistes', '0002_paneliste_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneliste',
            name='bio',
            field=models.TextField(verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='paneliste',
            name='date_presentation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la présentation'),
        ),
        migrations.AddField(
            model_name='paneliste',
            name='duree_presentation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='paneliste',
            name='heure_presentation',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de la présentation'),
        ),
        migrations.AddField(
            model_name='paneliste',
            name='resume_presentation',
            field=models.TextField(verbose_name='Résumé de la présentation'),
        ),
    ]
