# Generated by Django 4.2.26 on 2025-12-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturePitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_porteur', models.CharField(max_length=100, verbose_name='Nom du porteur')),
                ('prenom_porteur', models.CharField(max_length=100, verbose_name='Prénom du porteur')),
                ('email', models.EmailField(max_length=254)),
                ('indicatif_pays', models.CharField(max_length=10, verbose_name='Indicatif téléphonique')),
                ('telephone', models.CharField(max_length=20)),
                ('pays_residence', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('pays_origine', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('pays_impact', models.CharField(max_length=100, verbose_name="Pays d'impact du projet")),
                ('nom_projet', models.CharField(max_length=200, verbose_name='Nom du projet/entreprise')),
                ('domaine_activite', models.CharField(max_length=200, verbose_name="Domaine d'activité")),
                ('resume_executif', models.TextField(max_length=500, verbose_name='Résumé exécutif (pitch)')),
                ('financement_recherche', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Financement recherché (EUR)')),
                ('lien_video', models.URLField(blank=True, verbose_name='Lien vidéo de présentation')),
                ('document_pitch', models.FileField(upload_to='pitch_documents/', verbose_name='Document de Pitch')),
                ('business_plan', models.FileField(upload_to='pitch_documents/', verbose_name='Business Plan')),
                ('declaration_acceptee', models.BooleanField(default=False, verbose_name='Déclaration acceptée')),
                ('frais_dossier', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Frais de dossier (€)')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('selected', 'Sélectionné'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('note_evaluation', models.TextField(blank=True, verbose_name="Notes d'évaluation")),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score /100')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidature Pitch',
                'verbose_name_plural': 'Candidatures Pitch',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
