# Generated by Django 4.2.26 on 2025-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturepitch',
            name='document_presentation',
            field=models.FileField(blank=True, null=True, upload_to='pitch_documents/', verbose_name="Document de présentation de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturepitch',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='pitch_documents/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturepitch',
            name='nombre_projets_realises',
            field=models.IntegerField(blank=True, help_text='De 1 à 25', null=True, verbose_name='Nombre de projets réalisés'),
        ),
        migrations.AlterField(
            model_name='candidaturepitch',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='pitch_documents/', verbose_name='Business Plan - Déprécié'),
        ),
        migrations.AlterField(
            model_name='candidaturepitch',
            name='document_pitch',
            field=models.FileField(blank=True, null=True, upload_to='pitch_documents/', verbose_name='Document de Pitch - Déprécié'),
        ),
        migrations.AlterField(
            model_name='candidaturepitch',
            name='financement_recherche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Financement recherché (EUR) - Déprécié'),
        ),
    ]
