# Generated by Django 4.2.26 on 2025-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(max_length=200, verbose_name="Secteur d'activité")),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('nom_contact', models.CharField(max_length=200, verbose_name='Nom du contact')),
                ('fonction_contact', models.CharField(max_length=200, verbose_name='Fonction du contact')),
                ('telephone_contact', models.CharField(max_length=50, verbose_name='Téléphone du contact')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('type_stand', models.CharField(choices=[('6m2', 'Stand 6m² - Standard'), ('9m2', 'Stand 9m² - Populaire'), ('12m2', 'Stand 12m² - Premium'), ('18m2', 'Stand 18m² - VIP')], max_length=10, verbose_name='Type de stand')),
                ('nombre_stands', models.PositiveIntegerField(default=1, verbose_name='Nombre de stands')),
                ('mobilier_supplementaire', models.BooleanField(default=False, verbose_name='Mobilier supplémentaire')),
                ('eclairage_supplementaire', models.BooleanField(default=False, verbose_name='Éclairage supplémentaire')),
                ('branchement_electrique', models.BooleanField(default=False, verbose_name='Branchement électrique')),
                ('connexion_internet', models.BooleanField(default=False, verbose_name='Connexion Internet')),
                ('besoins_specifiques', models.TextField(blank=True, verbose_name='Besoins spécifiques / Commentaires')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
