# Generated by Django 4.2.26 on 2025-12-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationTombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('nombre_tickets', models.IntegerField(default=1, verbose_name='Nombre de tickets')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total (€)')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('numeros_tickets', models.TextField(blank=True, help_text='Numéros de tickets séparés par des virgules')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Participation Tombola',
                'verbose_name_plural': 'Participations Tombola',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
