# Generated by Django 4.2.26 on 2025-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationtombola',
            name='lot',
            field=models.CharField(choices=[('lot1', "Lot 1 - Billet d'avion (5€)"), ('lot2', 'Lot 2 - Terrain 300 m² (10€)')], default='lot1', max_length=10, verbose_name='Lot choisi'),
        ),
        migrations.AlterField(
            model_name='participationtombola',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Prix unitaire (€)'),
        ),
    ]
