# Generated by Django 4.2.26 on 2025-12-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'exposant")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='exposants/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('secteur', models.CharField(blank=True, max_length=200, null=True, verbose_name="Secteur d'activité")),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exposant',
                'verbose_name_plural': 'Exposants',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Code pays (ISO)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du pays')),
                ('code_drapeau', models.CharField(blank=True, max_length=2, null=True, verbose_name='Code pour drapeau (flagcdn)')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Representant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('titre', models.CharField(default='Représentant SIAB', max_length=200, verbose_name='Titre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='representants/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pays', models.ManyToManyField(related_name='representants', to='organisations.pays', verbose_name='Pays représentés')),
            ],
            options={
                'verbose_name': 'Représentant',
                'verbose_name_plural': 'Représentants',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
