# Generated by Django 4.2.26 on 2025-12-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgePresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('nom_media', models.CharField(max_length=200, verbose_name='Nom du média')),
                ('type_media', models.CharField(choices=[('presse_ecrite', 'Presse écrite'), ('presse_en_ligne', 'Presse en ligne'), ('media_tv', 'Média TV'), ('radio', 'Radio')], max_length=20, verbose_name='Type de média')),
                ('pays_origine_media', models.CharField(max_length=100, verbose_name="Pays d'origine du média")),
                ('code_pays', models.CharField(max_length=100, verbose_name='Code Pays')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Votre message')),
                ('emails_collaborateurs', models.TextField(blank=True, help_text='Un email par ligne', verbose_name='Emails des collaborateurs')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('badge_delivre', models.BooleanField(default=False, verbose_name='Badge délivré')),
            ],
            options={
                'verbose_name': 'Badge Presse',
                'verbose_name_plural': 'Badges Presse',
                'ordering': ['-date_demande'],
            },
        ),
    ]
