# Generated by Django 4.2.26 on 2025-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeVisiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code_pays', models.CharField(max_length=100, verbose_name='Code Pays')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('badge_envoye', models.BooleanField(default=False, verbose_name='Badge envoyé')),
            ],
            options={
                'verbose_name': 'Badge Visiteur',
                'verbose_name_plural': 'Badges Visiteurs',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
