# Generated by Django 4.2.26 on 2025-12-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgevisiteur',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
    ]
