# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteurs', '0002_badgevisiteur_message_badgevisiteur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgevisiteur',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='profession_autre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profession (autre)'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='sexe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name="Tranche d'âge"),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='type_biens_services',
            field=models.TextField(blank=True, verbose_name='Type de biens ou services recherchés'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='source_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comment avez-vous entendu parler du SIAB'),
        ),
        migrations.AddField(
            model_name='badgevisiteur',
            name='banques_africaines',
            field=models.CharField(blank=True, max_length=150, verbose_name='Importance des banques africaines'),
        ),
    ]
